flush ruleset

table inet firewall {
    define WAN_IF = wlo1
    define QEMU_BRIDGE = virbr0
    define QEMU_SUBNET = 192.168.100.0/24

    define SSH_PORT = 22
    define MDNS_PORT = 5353
    define DHCP_PORT = 67
    define DNS_PORT = 53

    set lan_interfaces {
        type ifname
        elements = { $WAN_IF }
    }

    set masquerade_subnets {
        type ipv4_addr
        flags interval
        elements = { $QEMU_SUBNET }
    }

    set kdeconnect_ports {
        type inet_service
        flags interval
        elements = { 1714-1764 }
    }

    set onion_services_ports {
        type inet_service
        elements = { 18084, 18089, 143, 993, 110, 995, 25 }
    }

    chain inbound_ipv4 {
        icmp type echo-request limit rate 5/second accept
        tcp dport @onion_services_ports skuid tor counter accept
    }

    chain inbound_ipv6 {
        icmpv6 type { nd-neighbor-solicit, nd-router-advert, nd-neighbor-advert } accept
        icmpv6 type echo-request limit rate 5/second accept
        tcp dport @onion_services_ports skuid tor counter accept
    }

    chain outbound_ipv4 {
        ip protocol tcp meta skuid tor counter accept
    }

    chain outbound_ipv6 {
        ip protocol tcp meta skuid tor counter accept
    }

    chain inbound {
        type filter hook input priority 0; policy drop;

        ct state vmap {
            established : accept,
            related : accept,
            invalid : drop
        }

        iifname lo accept

        meta protocol vmap {
            ip : jump inbound_ipv4,
            ip6 : jump inbound_ipv6
        }

        tcp dport vmap {
            $SSH_PORT : jump ssh_chain,
            80 : accept,
            443 : accept,
        }

        udp dport vmap {
            $MDNS_PORT : jump mdns_input,
            $DNS_PORT : accept,
            $DHCP_PORT : accept
        }

        tcp dport @kdeconnect_ports jump kdeconnect_in
        udp dport @kdeconnect_ports jump kdeconnect_in
    }

    chain outbound {
        type filter hook output priority 0; policy accept;
        udp sport vmap {
            5353 : jump mdns_output
        }

        udp dport vmap {
            5353 : jump mdns_output
        }

        meta protocol vmap {
            ip : jump outbound_ipv4,
            ip6 : jump outbound_ipv6
        }
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
        ct state vmap {
            established : accept,
            related : accept,
            invalid : drop
        }

        iifname vmap {
            $WAN_IF : jump from_wan,
            $QEMU_BRIDGE : jump from_qemu
        }
    }

    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept
        ip saddr @masquerade_subnets jump masquerade_qemu
    }

    chain ssh_chain {
        ct state new accept
    }

    chain mdns_input {
        ip daddr 224.0.0.251 iifname @lan_interfaces accept
        ip6 daddr ff02::fb iifname @lan_interfaces accept
        log prefix "mdns-input-deny: " drop
    }

    chain mdns_output {
        ip daddr 224.0.0.251 iifname @lan_interfaces accept
        ip6 daddr ff02::fb iifname @lan_interfaces accept
        udp sport 5353 oifname @lan_interfaces accept
        log prefix "mdns-output-deny: " drop
    }

    chain from_wan {
        oifname $QEMU_BRIDGE ct state new accept
    }

    chain from_qemu {
        oifname $WAN_IF ct state new accept
    }

    chain masquerade_qemu {
        oifname $WAN_IF masquerade
    }

    chain kdeconnect_in {
        iifname @lan_interfaces accept
        log prefix "KDE Connect blocked: " drop
    }
}
